# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[package]
name = "hotshot-query-service"
version = "0.0.7"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["file-system-data-source", "metrics-data-source", "sql-data-source"]
file-system-data-source = ["atomic_store"]
metrics-data-source = []
sql-data-source = ["anyhow", "include_dir", "refinery", "serde_json", "tokio", "tokio-postgres"]
testing = ["espresso-macros", "hotshot-testing", "portpicker", "rand", "spin_sleep", "tempdir"]

[[example]]
name = "simple-server"
required-features = ["sql-data-source", "testing"]

[dependencies]
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer.git", tag = "1.4.1", features = [
    "logging-utils",
] }
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
async-trait = "0.1"
bincode = "1.3"
clap = { version = "4.4", features = ["derive", "env"] }
commit = { git = "https://github.com/EspressoSystems/commit.git" }
custom_debug = "0.5"
derivative = "2.2"
derive_more = "0.99"
either = "1.8"
futures = "0.3"
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "0034ca55e1ebb9fb9cae4dfc3941cd5ebf1637ab" }
hotshot-signature-key = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "0034ca55e1ebb9fb9cae4dfc3941cd5ebf1637ab" }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "0034ca55e1ebb9fb9cae4dfc3941cd5ebf1637ab" }
hotshot-utils = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "0034ca55e1ebb9fb9cae4dfc3941cd5ebf1637ab" }
itertools = "0.12"
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.7", features = ["backtraces"] }
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco.git", tag = "v0.4.4" }
time = "0.3"
toml = "0.8"
tracing = "0.1"

# Dependencies enabled by feature "file-system-data-source".
atomic_store = { git = "https://github.com/EspressoSystems/atomicstore.git", tag = "0.1.3", optional = true }

# Dependencies enabled by feature "sql-data-source".
anyhow = { version = "1.0", optional = true }
include_dir = { version = "0.7", optional = true }
refinery = { version = "0.8", features = ["tokio-postgres"], optional = true }
serde_json = { version = "1.0", optional = true }
tokio = { version = "1.35", optional = true }
tokio-postgres = { version = "0.7", optional = true, default-features = false, features = [ # disabling the default features removes dependence on the tokio runtime
	"with-serde_json-1",
	"with-time-0_3",
] }

# Dependencies enabled by feature "testing".
espresso-macros = { git = "https://github.com/EspressoSystems/espresso-macros.git", tag = "0.1.0", optional = true }
hotshot-testing = { git = "https://github.com/EspressoSystems/HotShot.git", rev = "0034ca55e1ebb9fb9cae4dfc3941cd5ebf1637ab", optional = true }
portpicker = { version = "0.1", optional = true }
rand = { version = "0.8", optional = true }
spin_sleep = { version = "1.1", optional = true }
tempdir = { version = "0.3", optional = true }

# Dependencies enabled by feature "backtrace-on-stack-overflow".
#
# This feature allows unit tests to print out a backtrace if they overflow their stack. The
# implementation may trigger undefined behavior, so it is only used in tests and requires its own
# separate feature flag; it is not enabled just by using the "testing" feature.
#
# This feature is not supported on Windows because it uses Unix-style signal handling to catch
# stack overflow exceptions.
[target.'cfg(not(windows))'.dependencies]
backtrace-on-stack-overflow = { version = "0.3", optional = true }

[dev-dependencies]
espresso-macros = { git = "https://github.com/EspressoSystems/espresso-macros.git", tag = "0.1.0" }
portpicker = "0.1"
rand = "0.8"
spin_sleep = "1.1"
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco.git", tag = "v0.4.3" }
tempdir = "0.3"
