# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[package]
name = "hotshot-query-service"
version = "0.0.16"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["file-system-data-source", "metrics-data-source", "sql-data-source"]

# Enable the availability data source backed by the local file system.
file-system-data-source = ["atomic_store"]

# Enable a lightweight data source for status APIs without the archival availability API.
metrics-data-source = []

# Enable a mock persistence layer which doesn't actually persist anything.
#
# This is useful for adversarial testing, as it can be used to test the behavior of the query
# service where data is never available locally and must always be fetched on demand from a peer
# query service.
no-storage = []

# Enable the availability data source backed by a Postgres database.
sql-data-source = [
	"include_dir",
	"native-tls",
	"postgres-native-tls",
	"refinery",
	"tokio",
	"tokio-postgres",
]

# Enable extra features useful for writing tests with a query service.
testing = [
	"espresso-macros",
	"hotshot-example-types",
	"portpicker",
	"rand",
	"spin_sleep",
	"tempfile",
]

[[example]]
name = "simple-server"
required-features = ["sql-data-source", "testing"]

[dependencies]
anyhow = "1.0"
ark-serialize = "0.4.2"
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer.git", tag = "1.4.1", features = [
	"logging-utils",
] }
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
async-trait = "0.1"
bincode = "1.3"
bit-vec = { version = "0.6.3", features = ["serde_std"] }
chrono = "0.4"
clap = { version = "4.5", features = ["derive", "env"] }
cld = "0.5"
commit = { git = "https://github.com/EspressoSystems/commit.git" }
custom_debug = "0.6"
derivative = "2.2"
derive_more = "0.99"
either = "1.10"
futures = "0.3"
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.27" }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.27" }
itertools = "0.12.1"
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.2" }
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.8"
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco.git", tag = "v0.5.0" }
tagged-base64 = { git = "https://github.com/EspressoSystems/tagged-base64", tag = "0.3.4" }
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco.git", tag = "v0.5.0" }
time = "0.3"
toml = "0.8"
tracing = "0.1"
trait-variant = "0.1"
typenum = "1"
versioned-binary-serialization = { git = "https://github.com/EspressoSystems/versioned-binary-serialization.git", tag = "0.1.2" }

# Dependencies enabled by feature "file-system-data-source".
atomic_store = { git = "https://github.com/EspressoSystems/atomicstore.git", tag = "0.1.3", optional = true }

# Dependencies enabled by feature "sql-data-source".
include_dir = { version = "0.7", optional = true }
native-tls = { version = "0.2", optional = true }
postgres-native-tls = { version = "0.5", optional = true }
refinery = { version = "0.8", features = ["tokio-postgres"], optional = true }
tokio = { version = "1.36", optional = true }
tokio-postgres = { version = "0.7", optional = true, default-features = false, features = [ # disabling the default features removes dependence on the tokio runtime
	"with-serde_json-1",
	"with-time-0_3",
	"with-bit-vec-0_6",
] }

# Dependencies enabled by feature "testing".
espresso-macros = { git = "https://github.com/EspressoSystems/espresso-macros.git", tag = "0.1.0", optional = true }
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.27", optional = true }
portpicker = { version = "0.1", optional = true }
rand = { version = "0.8", optional = true }
spin_sleep = { version = "1.2", optional = true }
tempfile = { version = "3.10", optional = true }

# Dependencies enabled by feature "backtrace-on-stack-overflow".
#
# This feature allows unit tests to print out a backtrace if they overflow their stack. The
# implementation may trigger undefined behavior, so it is only used in tests and requires its own
# separate feature flag; it is not enabled just by using the "testing" feature.
#
# This feature is not supported on Windows because it uses Unix-style signal handling to catch
# stack overflow exceptions.
[target.'cfg(not(windows))'.dependencies]
backtrace-on-stack-overflow = { version = "0.3", optional = true }

[dev-dependencies]
espresso-macros = { git = "https://github.com/EspressoSystems/espresso-macros.git", tag = "0.1.0" }
generic-array = "0.14"
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.27" }
portpicker = "0.1"
rand = "0.8"
spin_sleep = "1.2"
surf = "2.3"
tempfile = "3.10"
