# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the HotShot Query Service library.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program. If not,
# see <https://www.gnu.org/licenses/>.

[package]
name = "hotshot-query-service"
version = "0.0.5"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"

[features]
default = []
testing = ["rand", "tempdir", "jf-primitives"]

[dependencies]
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer.git", tag = "1.2.0", features = ["async-std-executor", "logging-utils"] }
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
atomic_store = { git = "https://github.com/EspressoSystems/atomicstore.git", tag = "0.1.3" }
bincode = "1.3"
clap = { version = "4.3", features = ["derive", "env"] }
commit = { git = "https://github.com/EspressoSystems/commit.git", tag = "0.2.2" }
custom_debug = "0.5"
derive_more = "0.99"
either = "1.8"
futures = "0.3"
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", features = ["async-std-executor", "channel-async-std"] }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", features = ["async-std-executor", "channel-async-std"] }
hotshot-utils = { git = "https://github.com/EspressoSystems/HotShot.git" }
itertools = "0.10"
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.7", features = ["backtraces"] }
spin_sleep = "1.1"
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco.git", tag = "v0.4.1" }
toml = "0.5"
tracing = "0.1"

# Dependencies enabled by feature "testing".
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish.git", tag = "0.1.2-patch.1", optional = true }
rand = { version = "0.8", optional = true }
tempdir = { version = "0.3", optional = true }

# Dependencies enabled by feature "backtrace-on-stack-overflow".
#
# This feature allows unit tests to print out a backtrace if they overflow their stack. The
# implementation may trigger undefined behavior, so it is only used in tests and requires its own
# separate feature flag; it is not enabled just by using the "testing" feature.
#
# This feature is not supported on Windows because it uses Unix-style signal handling to catch
# stack overflow exceptions.
[target.'cfg(not(windows))'.dependencies]
backtrace-on-stack-overflow = { version = "0.3", optional = true }

[dev-dependencies]
portpicker = "0.1"
rand = "0.8"
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco.git", tag = "v0.4.1" }
tempdir = "0.3"
