[advisories]
ignore = [
    # remove_dir_all (used by deprecated tempdir crate)
    "RUSTSEC-2023-0018",
    # DoS in WebPKI that comes with tide_disco
    "RUSTSEC-2023-0052",
    # Tungstenite allows remote attackers to cause a denial of service
    # Dependency of async-tungstenite -> tide-websockets / surf-disco
    "RUSTSEC-2023-0065",
]
