name: Security audit
on:
  push:
    # For PR we only want to fail if dependencies were changed.
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  # Run the audit job once a day on main.
  schedule:
    - cron: "0 0 * * *"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # See https://github.com/marketplace/actions/rust-audit-check for docs
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
